# Bag of word(BOW)

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [4]:
bow = cv.fit_transform(df["text"])

In [22]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [6]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [8]:
#new
cv.transform(["Bappy watch dswithbappy"]).toarray()

array([[0, 1, 0, 1, 0]])

In [9]:
X= bow.toarray()
y= df['output']

# N-grams

In [27]:
cv = CountVectorizer(ngram_range=(2,2))

In [28]:
bow = cv.fit_transform(df['text'])

In [29]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [30]:
bow.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

# TF-IDF (Term frequency- Inverse document frequency)

In [31]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [34]:
arr = tfidf.fit_transform(df['text'])

In [35]:
arr.toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

# Word2vec

In [75]:
import numpy as np
import pandas as pd
import gensim
import os
import nltk

In [76]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [112]:
story = []
for filename in os.listdir('data'):
    if filename == '.ipynb_checkpoints':
      pass
    f = open(os.path.join('data',filename))
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [113]:
story[0]

['game',
 'of',
 'thrones',
 'book',
 'one',
 'of',
 'song',
 'of',
 'ice',
 'and',
 'fire',
 'by',
 'george',
 'martin',
 'prologue',
 'we',
 'should',
 'start',
 'back',
 'gared',
 'urged',
 'as',
 'the',
 'woods',
 'began',
 'to',
 'grow',
 'dark',
 'around',
 'them']

In [114]:
model = gensim.models.Word2Vec(window = 10,min_count=2)

In [115]:
model.build_vocab(story)

In [116]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(1059241, 1423500)

In [117]:
model.wv.most_similar('arya')

[('sansa', 0.9851764440536499),
 ('bran', 0.982503354549408),
 ('dany', 0.9758516550064087),
 ('jon', 0.9610734581947327),
 ('herself', 0.9519559144973755),
 ('feel', 0.9501200318336487),
 ('moment', 0.945041835308075),
 ('she', 0.9449124932289124),
 ('again', 0.9431681036949158),
 ('uncomfortable', 0.9416856169700623)]

In [118]:
model.wv.similarity('arya','sansa')

np.float32(0.98517656)

In [119]:
vec = model.wv.get_normed_vectors()
vec.shape,vec

((7432, 100),
 array([[-0.0550015 ,  0.07037918, -0.03580999, ..., -0.09467271,
         -0.02260152,  0.14440171],
        [-0.03237965,  0.10502315, -0.02510951, ..., -0.16635406,
          0.05326319,  0.11765441],
        [-0.14247054, -0.00760304,  0.05259115, ..., -0.09664685,
          0.04037633, -0.10283312],
        ...,
        [ 0.11131635, -0.09729847,  0.01581988, ..., -0.0787511 ,
          0.03019987, -0.04125876],
        [-0.13082382, -0.04160128,  0.06173045, ..., -0.01023132,
         -0.08796662, -0.1456027 ],
        [-0.05799967,  0.11532511,  0.02600656, ..., -0.1097145 ,
          0.03775398, -0.05143194]], dtype=float32))

# visualization- PCA

In [120]:
from sklearn.decomposition import PCA # To reduce the dimensionality

In [121]:
pca = PCA(n_components=3)

In [126]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [127]:
X

array([[-0.37663597, -0.13884914,  0.33782202],
       [-0.4523756 , -0.05300742,  0.10978264],
       [ 0.4553951 , -0.14787567, -0.01963428],
       ...,
       [-0.39921945, -0.7555504 ,  0.2398923 ],
       [ 0.552374  , -0.28838325,  0.49957332],
       [ 0.09610743,  0.09926808,  0.12565854]], dtype=float32)

In [128]:
X.shape

(7432, 3)

In [136]:
import plotly.express as px
fig = px.scatter_3d(X[200:300],x=0,y=1,z=2, color=y[200:300])
fig.show()

ValueError: All arguments should have the same length. The length of argument `color` is 0, whereas the length of  previously-processed arguments ['0', '1', '2'] is 100